import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task,
# which you should run after static files are built and
# before starting your production server.
config :agent_kill_switch, AgentKillSwitchWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support - TEMPLATE FOR PRODUCTION
#
# To get SSL working, you will need to add the `https` configuration
# to the previous section and set your `:url` port to 443:
#
#     config :agent_kill_switch, AgentKillSwitchWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: "priv/cert/selfsigned_key.pem",
#         certfile: "priv/cert/selfsigned.pem"
#       ]
#
# The `http:` config above can be replaced with:
#
#     https: [
#       ...,
#       port: 443,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem",
#       otp_app: :agent_kill_switch
#     ]
#
# Where those certs are generated by running:
#
#     $ mix phx.gen.cert
